format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$fill\
$cmd_duration\
$nix_shell\
$kubernetes\
$aws\
$azure\
$line_break\
$character
"""

add_newline = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[aws]
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style)'
symbol = "   "

[azure]
format = '[$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'
disabled = false

[cmd_duration]
format = '[⏱ $duration]($style)'

[directory]
read_only = " "
truncation_symbol = '../'

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style)'
symbol = ' 󱃾 '
style = 'blue'
disabled = false

[nix_shell]
disabled = false
symbol = '❄️ '
style = 'blue'
format = '[$state( \($name\))](bold blue)'
